sudo: required

language: cpp

before_install:
    sudo apt-get -qq update

    sudo apt-get install -y cpputest

script:
    autoreconf -if && ./configure --enable-tests && make && make check

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
