sudo: required

language: cpp

before_install: git clone git://github.com/cpputest/cpputest.git && cd cpputest && autoreconf -if && ./configure && make && sudo make install

script:
    - cd autotools_template
    - autoreconf -if
    - ./configure --enable-tests
    - make
    - make check
